force-app/main/default/objects/Account/fields/RendaMensal__c.field-meta.xml
<CustomField>
    <fullName>RendaMensal__c</fullName>
    <label>Renda Mensal</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>COMP-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>CompradoresConta</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CompradorSelector.cls
public with sharing class CompradorSelector {
    public static List<Comprador__c> getByOportunidade(Id oportunidadeId) {
        return [
            SELECT
                Conta__c,
                Conta__r.Name,
                Conta__r.RendaMensal__c,
                Conta__r.Phone
            FROM Comprador__c
            WHERE Oportunidade__c = :oportunidadeId
            ORDER BY Conta__r.Name ASC
        ];
    }
}