force-app/main/default/objects/Transacao__c/Transacao__c.object-meta.xml
<CustomObject>
    <label>Transação</label>
    <nameField>
        <label>Transação Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transacao__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Frequencia__c.field-meta.xml
<CustomField>
    <fullName>Frequencia__c</fullName>
    <label>Frequência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensal</fullName>
                <default>true</default>
                <label>Mensal</label>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Semanal</fullName>
                <isActive>false</isActive>
                <label>Semanal</label>
            </value>
            <value>
                <fullName>Unica</fullName>
                <isActive>false</isActive>
                <label>Unica</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Recorrente__c.field-meta.xml
<CustomField>
    <fullName>Recorrente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recorrente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entrada</fullName>
            </value>
            <value>
                <fullName>Saída</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransferenciaService.cls
public without sharing class TransferenciaService {
     

   public static void realizarTransferencia(Transacao__c novaTransferencia) {

    if (novaTransferencia == null) {
        throw new AuraHandledException('A transferência não pode ser nula.');
    }

    Id recordTypeId = Schema.SObjectType.Transacao__c
        .getRecordTypeInfosByName()
        .get(novaTransferencia.Tipo__c)
        .getRecordTypeId();

    novaTransferencia.RecordTypeId = recordTypeId;

    List<Transacao__c> lista = new List<Transacao__c>();

    if (!novaTransferencia.Recorrente__c) {
        lista.add(novaTransferencia);
    } 
    else {

        Integer quantidade = 1;
        Integer mesesIncremento = 0;

        if (novaTransferencia.Frequencia__c == 'Mensal') {
            quantidade = 12;
            mesesIncremento = 1;
        }
        else if (novaTransferencia.Frequencia__c == 'Semestral') {
            quantidade = 2;
            mesesIncremento = 6;
        }
        else if (novaTransferencia.Frequencia__c == 'Anual') {
            quantidade = 3;
        }

        for (Integer i = 0; i < quantidade; i++) {

            Transacao__c nova = novaTransferencia.clone(false, true, false, false);

            if (novaTransferencia.Frequencia__c == 'Anual') {
                nova.Data__c = novaTransferencia.Data__c.addYears(i);
            } else {
                nova.Data__c = novaTransferencia.Data__c.addMonths(i * mesesIncremento);
            }

            lista.add(nova);
        }
    }

    insert lista;
}


    public static  List<Transacao__c> getTransacoesPorUsuarioEData(String data) {
        List<String> partesData = data.split('-');
        Integer ano = Integer.valueOf(partesData[0]);
        Integer mes = Integer.valueOf(partesData[1]);
        Date dataInicio = Date.newInstance(ano, mes, 1);
        Date dataFim = dataInicio.addMonths(1).addDays(-1);
        return TransferenciaSelector.buscarTransferenciasPorUsuarioEData(dataInicio, dataFim);
    }
}