force-app/main/default/objects/Transacao__c/Transacao__c.object-meta.xml
<CustomObject>
    <label>Transação</label>
    <nameField>
        <label>Transação Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categorias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entrada</fullName>
            </value>
            <value>
                <fullName>Saída</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransferenciaSelector.cls
public without sharing class TransferenciaSelector {
   

    public static List<Transacao__c> buscarTransferenciasPorUsuario() {
        return [SELECT Id, Name, Valor__c, Data__c, Tipo__c, RecordTypeId FROM Transacao__c WHERE OwnerId = :UserInfo.getUserId()  ];
    }

    public static List<Transacao__c> buscarTransferenciasPorUsuarioEData(Date dataInicio, Date dataFim) {
        return [SELECT Id, Name, Valor__c, Data__c, Tipo__c,Categoria__c,  RecordTypeId FROM Transacao__c WHERE OwnerId = :UserInfo.getUserId() AND Data__c >= :dataInicio AND Data__c <= :dataFim];
    }
}